"""empty message

Revision ID: 3b746a6ce561
Revises: 5e9126c7f618
Create Date: 2021-04-17 22:38:30.597837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3b746a6ce561'
down_revision = '5e9126c7f618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('mass', sa.String(length=80), nullable=False),
    sa.Column('height', sa.String(length=80), nullable=False),
    sa.Column('hair_color', sa.String(length=50), nullable=False),
    sa.Column('skin_color', sa.String(length=60), nullable=False),
    sa.Column('eye_color', sa.String(length=80), nullable=False),
    sa.Column('birth_year', sa.String(length=80), nullable=False),
    sa.Column('gender', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_index('name', table_name='characters')
    op.drop_table('characters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('mass', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('height', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('hair_color', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('skin_color', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('eye_color', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('birth_year', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('gender', mysql.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'characters', ['name'], unique=True)
    op.drop_table('personajes')
    # ### end Alembic commands ###
